import { Command } from 'commander';
import fs from 'fs/promises';
import path from 'path';
import chalk from 'chalk';
import { configManager } from '../core/config.js';
import { GitService } from '../core/git.js';
import { AIService } from '../core/ai.js';
import { ReportOptions } from '../types/index.js';

export const reportCommand = new Command('report')
  .description('Generate accomplishment report from git commits')
  .option('-s, --since <date>', 'Include commits since this date (YYYY-MM-DD)')
  .option('-u, --until <date>', 'Include commits until this date (YYYY-MM-DD)')
  .option('-o, --output <path>', 'Output file path')
  .option('-f, --format <format>', 'Output format (markdown|json)', 'markdown')
  .action(async (options: ReportOptions) => {
    try {
      // Load configuration
      const config = await configManager.loadConfig();
      if (!config) {
        console.error(chalk.red('❌ No configuration found.'));
        console.log(chalk.blue('Run "devsum setup" first to configure your settings.'));
        process.exit(1);
      }

      // Validate git repository
      const gitService = new GitService();
      const isGitRepo = await gitService.isGitRepository();
      if (!isGitRepo) {
        console.error(chalk.red('❌ Not a git repository.'));
        console.log(chalk.gray('Please run this command from within a git repository.'));
        process.exit(1);
      }

      console.log(chalk.blue('📊 Generating accomplishment report...\n'));

      // Get git commits
      console.log(chalk.gray('🔍 Fetching git commits...'));
      const commits = await gitService.getCommits(options.since, options.until);
      
      if (commits.length === 0) {
        console.log(chalk.yellow('⚠️  No commits found in the specified date range.'));
        process.exit(0);
      }

      console.log(chalk.green(`✅ Found ${commits.length} commits`));

      // Generate AI report
      console.log(chalk.gray('🤖 Generating AI summary...'));
      const aiService = new AIService(config);
      const report = await aiService.generateReport(commits);

      // Prepare output
      const outputPath = options.output || 
        path.join(config.defaultOutput, `report-${new Date().toISOString().split('T')[0]}.md`);
      
      // Ensure output directory exists
      await fs.mkdir(path.dirname(outputPath), { recursive: true });

      // Generate report content
      const branch = await gitService.getCurrentBranch();
      const reportContent = generateMarkdownReport(report, commits, {
        since: options.since,
        until: options.until,
        branch,
        generatedAt: new Date().toISOString(),
      });

      // Save report
      await fs.writeFile(outputPath, reportContent);

      console.log(chalk.green(`\n✅ Report generated successfully!`));
      console.log(chalk.blue(`📄 Saved to: ${outputPath}`));
      console.log(chalk.gray(`📊 Analyzed ${commits.length} commits from branch "${branch}"`));

    } catch (error) {
      console.error(chalk.red('❌ Failed to generate report:'));
      console.error(chalk.red(error instanceof Error ? error.message : 'Unknown error'));
      process.exit(1);
    }
  });

function generateMarkdownReport(
  report: any,
  commits: any[],
  metadata: {
    since?: string;
    until?: string;
    branch: string;
    generatedAt: string;
  }
): string {
  const dateRange = metadata.since 
    ? `${metadata.since}${metadata.until ? ` to ${metadata.until}` : ' to present'}`
    : 'Recent commits';

  return `# Development Accomplishment Report

**Generated:** ${new Date(metadata.generatedAt).toLocaleString()}  
**Branch:** ${metadata.branch}  
**Period:** ${dateRange}  
**Commits Analyzed:** ${commits.length}

---

## Summary

${report.summary}

## Key Accomplishments

${report.accomplishments.map((acc: string) => `- ${acc}`).join('\n')}

${report.recommendations ? `## Recommendations

${report.recommendations.map((rec: string) => `- ${rec}`).join('\n')}

` : ''}---

## Commit Details

${commits.slice(0, 10).map(commit => 
  `### ${commit.message}\n**Date:** ${commit.date.split('T')[0]}  \n**Author:** ${commit.author}  \n**Files:** ${commit.files.slice(0, 5).join(', ')}${commit.files.length > 5 ? '...' : ''}\n`
).join('\n')}

${commits.length > 10 ? `\n*... and ${commits.length - 10} more commits*\n` : ''}

---

*Generated by DevSum CLI*
`;
}