import { GitCommit, ReportLength } from '../types/index.js';

export interface PlainTextReportMetadata {
  since?: string;
  until?: string;
  author?: string;
  branch: string;
  generatedAt: string;
  length?: string;
  commitsAnalyzed: number;
  authors: number;
  filesModified: number;
  dateRange: string;
}

export class PlainTextReportGenerator {
  generateReport(
    report: any,
    commits: GitCommit[],
    metadata: PlainTextReportMetadata
  ): string {
    const periodDescription = this.getPeriodDescription(metadata);
    const authorFilter = metadata.author ? ` (Author: ${metadata.author})` : '';

    return `DEVELOPMENT ACCOMPLISHMENT REPORT
Generated: ${new Date(metadata.generatedAt).toLocaleString()}
Branch: ${metadata.branch}
Period: ${periodDescription}${authorFilter}
Commits Analyzed: ${metadata.commitsAnalyzed}
${metadata.length && metadata.length !== 'detailed' ? `Report Length: ${metadata.length.charAt(0).toUpperCase() + metadata.length.slice(1)}` : ''}

${'='.repeat(80)}

EXECUTIVE SUMMARY

${report.summary.replace(/\*\*(.*?)\*\*/g, '$1')}

${'='.repeat(80)}

KEY ACCOMPLISHMENTS

${report.accomplishments?.map((acc: string) => `• ${acc.replace(/\*\*(.*?)\*\*/g, '$1')}`).join('\n') || '• No accomplishments identified'}

${report.technicalImprovements ? `${'='.repeat(80)}

TECHNICAL IMPROVEMENTS

${report.technicalImprovements.map((imp: string) => `• ${imp.replace(/\*\*(.*?)\*\*/g, '$1')}`).join('\n')}

` : ''}${report.recommendations ? `${'='.repeat(80)}

RECOMMENDATIONS

${report.recommendations.map((rec: string) => `• ${rec.replace(/\*\*(.*?)\*\*/g, '$1')}`).join('\n')}

` : ''}${'='.repeat(80)}

COMMIT ANALYSIS

${commits.slice(0, 15).map(commit => 
  `COMMIT: ${commit.message}
Date: ${commit.date.split('T')[0]}
Author: ${commit.author}
Files: ${commit.files.slice(0, 5).join(', ')}${commit.files.length > 5 ? ` (+${commit.files.length - 5} more)` : ''}
${commit.insertions || commit.deletions ? `Changes: +${commit.insertions || 0} -${commit.deletions || 0}` : ''}

`
).join('')}

${commits.length > 15 ? `... and ${commits.length - 15} more commits

` : ''}${'='.repeat(80)}

STATISTICS

Total Commits: ${commits.length}
Authors: ${metadata.authors}
Files Modified: ${metadata.filesModified}
Date Range: ${metadata.dateRange}

${metadata.since || metadata.until || metadata.author ? `${'='.repeat(80)}

APPLIED FILTERS

${metadata.since ? `Since: ${metadata.since.toLowerCase() === 'today' ? `today (${new Date().toISOString().split('T')[0]} 00:00:00 to now)` : metadata.since}` : ''}
${metadata.until ? `Until: ${metadata.until.toLowerCase() === 'today' ? `today (${new Date().toISOString().split('T')[0]} 23:59:59)` : metadata.until}` : ''}
${metadata.author ? `Author: ${metadata.author}` : ''}

` : ''}${'='.repeat(80)}

Generated by DevSum CLI
Powered by AI • Making developers productive
`;
  }

  private getPeriodDescription(metadata: PlainTextReportMetadata): string {
    if (!metadata.since) return 'All commits';

    let periodDescription = metadata.since;
    if (metadata.until) {
      periodDescription += ` to ${metadata.until}`;
    } else {
      periodDescription += ' to present';
    }

    // Enhanced period description with today support
    if (metadata.since?.toLowerCase() === 'today') {
      const now = new Date();
      const timeStr = now.toTimeString().split(' ')[0].substring(0, 5); // HH:MM format
      const todayDate = new Date().toISOString().split('T')[0];
      periodDescription = `Today (${todayDate} 00:00:00 to ${timeStr})`;
      if (metadata.until) {
        periodDescription += ` (until ${metadata.until})`;
      }
    } else if (metadata.until?.toLowerCase() === 'today') {
      const todayDate = new Date().toISOString().split('T')[0];
      periodDescription = periodDescription.replace('today', `today (until ${todayDate} 23:59:59)`);
    } else if (metadata.since && metadata.since.match(/^\d+[dwmy]$/)) {
      const unit = metadata.since.slice(-1);
      const num = metadata.since.slice(0, -1);
      const unitName = unit === 'd' ? 'days' : unit === 'w' ? 'weeks' : unit === 'm' ? 'months' : 'years';
      periodDescription = `Last ${num} ${unitName}`;
      if (metadata.until) {
        periodDescription += ` (until ${metadata.until})`;
      }
    }

    return periodDescription;
  }
}
